#!/usr/bin/env python3
"""Generate the Stash web favicon assets.

Writes the browser favicon set into Backend/Public/ in the full app-icon look:
a white bookmark-ribbon glyph (the same V-notched ribbon the native app and the
browser extension use) on an indigo (#231468) rounded square. This is the web
twin of Extension/icons/generate-icons.py and StashApp/icon/generate-app-icon.py;
all three share the ribbon proportions and the brand indigo.

Emits:
    favicon.svg          : scalable master, served for modern browsers
    favicon-32.png       : PNG fallback for <link rel="icon">
    apple-touch-icon.png : 180x180 home-screen icon
    favicon.ico          : multi-res 16/32/48 for the implicit /favicon.ico request

No external dependencies beyond Pillow. Run from the Backend/ folder:

    python3 Scripts/generate-web-icons.py
"""

from pathlib import Path

from PIL import Image, ImageDraw

INDIGO = (35, 20, 104, 255)  # #231468
WHITE = (255, 255, 255, 255)
SUPERSAMPLE = 8

# Ribbon geometry, matching the native app icon (StashApp/icon/generate-app-icon.py).
TOP, BOTTOM, NOTCH = 0.18, 0.82, 0.65
CORNER = 0.22  # rounded-square background radius, as a fraction of the side

PUBLIC = Path(__file__).resolve().parent.parent / "Public"


def ribbon_points(size):
    """The ribbon polygon, as (x, y) tuples in pixel space for a square canvas."""
    left, right = 0.30 * size, 0.70 * size
    return [
        (left, TOP * size),
        (right, TOP * size),
        (right, BOTTOM * size),
        (0.5 * size, NOTCH * size),
        (left, BOTTOM * size),
    ]


def render(size):
    canvas = size * SUPERSAMPLE
    image = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle(
        [0, 0, canvas - 1, canvas - 1],
        radius=CORNER * canvas,
        fill=INDIGO,
    )
    draw.polygon(ribbon_points(canvas), fill=WHITE)
    draw.rounded_rectangle(
        [0.30 * canvas, TOP * canvas, 0.70 * canvas, (TOP + 0.12) * canvas],
        radius=0.06 * canvas,
        fill=WHITE,
    )
    return image.resize((size, size), Image.LANCZOS)


def svg():
    """The favicon as a hand-tuned 128-unit vector (same look as the PNGs)."""
    return """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128">
  <!-- Stash favicon: white bookmark ribbon on an indigo (#231468) rounded square,
       matching the native app icon. Regenerated by Scripts/generate-web-icons.py. -->
  <rect width="128" height="128" rx="28.16" fill="#231468"/>
  <path fill="#ffffff"
        d="M46.08 23.04
           h35.84
           a7.68 7.68 0 0 1 7.68 7.68
           v74.24
           L64 83.2
           L38.4 104.96
           V30.72
           a7.68 7.68 0 0 1 7.68-7.68
           Z" />
</svg>
"""


def main():
    (PUBLIC / "favicon.svg").write_text(svg())
    print("wrote favicon.svg")

    render(32).save(PUBLIC / "favicon-32.png")
    print("wrote favicon-32.png")

    render(180).save(PUBLIC / "apple-touch-icon.png")
    print("wrote apple-touch-icon.png")

    render(48).save(
        PUBLIC / "favicon.ico",
        sizes=[(16, 16), (32, 32), (48, 48)],
    )
    print("wrote favicon.ico")


if __name__ == "__main__":
    main()
